### ISSUE TITLE
Increase links to github in iteration report

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/princeton-cdh.github.io#7]
For example: 

**Active projects**

- mep-django (0 points, 4 issues )

would link to: https://github.com/princeton-cdh/mep-django

and

**Releases**
- mep-django v1.2.2 — Thursday Jul 30, 2020

would link to: https://github.com/Princeton-CDH/mep-django/releases/tag/1.2.2

**Comment by rlskoeser** [comment]
@kmcelwee thanks for documenting the link structure, made this even easier.

I'm wondering about adding a link to the changelog as well — it *should* look something like this: https://github.com/Princeton-CDH/mep-django/blob/master/CHANGELOG.rst#122 

But I don't know how reliable that is. (Although I suppose if the anchor link fails you would still get to the page, which is probably enough... 🤔 )
